apiVersion: batch/v1
kind: CronJob
metadata:
  name: romain-cron
  namespace: romain
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: alpine/curl:3.14
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl what-an-url.default:8080 -d unlocker=romain
          restartPolicy: OnFailure
